services:
  mc:
    image: itzg/minecraft-server:java21
    container_name: fabric-mc
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.1"
      MEMORY: "7G"
      MOTD: "Fabric server on Docker"

      # Remote console (set the password in Railway env, not here)
      ENABLE_RCON: "true"
      RCON_PASSWORD: "changeme"
      RCON_PORT: "25575"

      TZ: "America/Chicago"
      USE_AIKAR_FLAGS: "true"
      VIEW_DISTANCE: "10"
      SIMULATION_DISTANCE: "8"
      MAX_PLAYERS: "10"
      ONLINE_MODE: "true"

      MODS_FILE: /extras/mods.txt
      REMOVE_OLD_MODS: "TRUE"

      # IMPORTANT: no Auto-Stop variables here
      ENABLE_QUERY: "true"   # keep this; helpful for player count / tools

    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
      - "25575:25575"

    volumes:
      - ./data:/data
      - ./extras/mods.txt:/extras/mods.txt:ro

    restart: unless-stopped     # restart on crash; does not interfere with sleep
    stop_grace_period: 2m

    tty: true
    stdin_open: true
