services:
  mc:
    image: itzg/minecraft-server:java21
    container_name: fabric-mc
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.1"
      MEMORY: "8G"
      MOTD: "Fabric server on Docker"

      ENABLE_RCON: "true"
      RCON_PASSWORD: "changeme"
      RCON_PORT: "25575"

      TZ: "America/Chicago"
      USE_AIKAR_FLAGS: "true"
      VIEW_DISTANCE: "10"
      SIMULATION_DISTANCE: "8"
      MAX_PLAYERS: "10"
      ONLINE_MODE: "true"
      MODS_FILE: /extras/mods.txt
      REMOVE_OLD_MODS: "TRUE"

      # --- Auto-stop BEFORE Railway's 10-min idle window ---
      ENABLE_AUTOSTOP: "TRUE"
      AUTOSTOP_TIMEOUT_EST: "300"    # 5 min after last player leaves
      AUTOSTOP_TIMEOUT_INIT: "480"   # 10 min if nobody ever joins
      AUTOSTOP_PERIOD: "10"          # check interval (secs)
      ENABLE_QUERY: "true"           # helps detect player count
  
      # Optional: run a save on a timer (see note below)
      # RCON_CMDS_ON_CONNECT: "save-all flush"

    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
      - "25575:25575"

    volumes:
      - ./data:/data
      - ./extras/mods.txt:/extras/mods.txt:ro

    # Let the server stop cleanly; don't auto-restart after autostop
    restart: "no"
    stop_grace_period: 2m

    tty: true
    stdin_open: true
