    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.1"
      MEMORY: "8G"
      MOTD: "Fabric server on Docker"

      ENABLE_RCON: "true"
      RCON_PASSWORD: "changeme"
      RCON_PORT: "25575"

      TZ: "America/Chicago"
      USE_AIKAR_FLAGS: "true"
      VIEW_DISTANCE: "10"
      SIMULATION_DISTANCE: "8"
      MAX_PLAYERS: "10"
      ONLINE_MODE: "true"

      MODS_FILE: /extras/mods.txt
      REMOVE_OLD_MODS: "TRUE"

      ENABLE_QUERY: "true"
      ALLOW_FLIGHT: "true"

      JVM_OPTS: >
        -Dfml.readTimeout=240
        -Dforge.loginTimeout=180
        -Dnet.minecraft.server.login.timeout=180
        -Djava.net.preferIPv4Stack=true
        -Dsun.net.client.defaultConnectTimeout=30000
        -Dsun.net.client.defaultReadTimeout=30000
      ENABLE_TCP_KEEPALIVE: "true"

    ports:
      - "25565:25565"
      - "25575:25575"

    sysctls:
      net.ipv4.tcp_keepalive_time: 60
      net.ipv4.tcp_keepalive_intvl: 10
      net.ipv4.tcp_keepalive_probes: 5
